version: '3.8'
services:
  rds_ws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: bot
        PASSWORD: ""
    network_mode: host
    privileged: true
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=42
      - TZ=America/New_York
      - CONTAINER_NAME=r-d-s-a
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/X11:/etc/X11
      - ../../../:/home/bot/rds_ws/:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    user: bot
    restart: always
    command: tail -f /dev/null
    working_dir: /home/bot

