"""Generate a downloadable ROS 2 bringup package for a robot."""
from __future__ import annotations

import io
import json
import zipfile
from xml.sax.saxutils import escape as xml_escape

from .models import RobotConfig


def package_name(robot: RobotConfig) -> str:
    return f"{robot.id}_bringup"


def render_package_xml(robot: RobotConfig) -> str:
    name = package_name(robot)
    return f"""<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>{xml_escape(name)}</name>
  <version>0.1.0</version>
  <description>Bringup for {xml_escape(robot.display_name)}, generated by the Robot Description Setup Assistant.</description>
  <maintainer email="user@example.com">generated</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>{xml_escape(robot.urdf_package)}</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""


def render_cmakelists(robot: RobotConfig) -> str:
    name = package_name(robot)
    return f"""cmake_minimum_required(VERSION 3.10)
project({name})

find_package(ament_cmake REQUIRED)

install(DIRECTORY launch DESTINATION share/${{PROJECT_NAME}})

ament_package()
"""


def render_view_launch(robot: RobotConfig) -> str:
    # Emit every interpolated value as a JSON-encoded Python string literal so
    # quotes, backslashes, or newlines in the catalog data cannot break or
    # inject into the generated launch file.
    pkg = json.dumps(robot.urdf_package)
    path = json.dumps(robot.urdf_path)
    # xacro_args are appended after the file path; a leading space separates them.
    args = json.dumps(f" {robot.xacro_args}" if robot.xacro_args else "")
    title = robot.display_name.replace('"', "'").replace("\n", " ")
    return f'''"""View {title}: robot_state_publisher + joint_state_publisher_gui."""
from launch import LaunchDescription
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    robot_description = ParameterValue(
        Command([
            "xacro ",
            PathJoinSubstitution(
                [FindPackageShare({pkg}), {path}]
            ),
            {args},
        ]),
        value_type=str,
    )

    return LaunchDescription([
        Node(
            package="robot_state_publisher",
            executable="robot_state_publisher",
            output="screen",
            parameters=[{{"robot_description": robot_description}}],
        ),
        Node(
            package="joint_state_publisher_gui",
            executable="joint_state_publisher_gui",
            output="screen",
        ),
    ])
'''


def render_readme(robot: RobotConfig) -> str:
    name = package_name(robot)
    return f"""# {name}

Generated bringup package for **{robot.display_name}** by the Robot Description
Setup Assistant.

## Use

Place this package in a ROS 2 workspace `src/`, then:

```bash
colcon build --packages-select {name}
. install/setup.bash
ros2 launch {name} view.launch.py
```

This starts `robot_state_publisher` (loading `{robot.urdf_package}/{robot.urdf_path}`)
and `joint_state_publisher_gui` so you can pose the robot. Visualize it in your
preferred tool (e.g. the web UI's live mode, or any TF/RobotModel viewer).
"""


def build_package_zip(robot: RobotConfig) -> bytes:
    name = package_name(robot)
    files = {
        f"{name}/package.xml": render_package_xml(robot),
        f"{name}/CMakeLists.txt": render_cmakelists(robot),
        f"{name}/launch/view.launch.py": render_view_launch(robot),
        f"{name}/README.md": render_readme(robot),
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, content in files.items():
            zf.writestr(path, content)
    return buf.getvalue()
